server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: postgresadmin
    password: postgresadmin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.value}

management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans